name: Build JNI

on:
  push:
    branches:
      - main # Или master, если у вас так называется основная ветка

jobs:
  build:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu для сборки

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Скачиваем ваш код из репозитория

    # --- НОВЫЙ ШАГ: Установка libncurses5 ---
    - name: Install libncurses5 (for old NDKs)
      run: |
        sudo apt-get update
        sudo apt-get install -y libncurses5
    # ----------------------------------------

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1 # Используем экшн для установки NDK
      with:
        ndk-version: r16b # Укажите версию NDK, которую вы использовали (r16b)

    - name: Build JNI
      run: |
        # Мы добавили clean, чтобы убедиться, что всегда происходит полная сборка.
        ndk-build -C . clean
        ndk-build -C .

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jni-compiled-libraries
        path: libs/ # Директория, куда ndk-build помещает скомпилированные библиотеки
