name: Build JNI Library with NDK r16b

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and Extract Android NDK r16b
      run: |
        NDK_URL="https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip"
        NDK_ROOT_FOLDER="android-ndk-r16b"
        NDK_DIR="$HOME/$NDK_ROOT_FOLDER"

        echo "Downloading NDK from $NDK_URL"
        curl -L "$NDK_URL" -o ndk.zip

        echo "Unzipping NDK to $HOME"
        unzip -q ndk.zip -d "$HOME"

        echo "Adding NDK to PATH and setting NDK_HOME"
        echo "$NDK_DIR" >> $GITHUB_PATH
        echo "NDK_HOME=$NDK_DIR" >> $GITHUB_ENV

        echo "Verifying ndk-build presence:"
        which ndk-build || echo "ndk-build not found in PATH yet (this is normal after adding to GITHUB_PATH)"
        if [ -f "$NDK_DIR/ndk-build" ]; then
          echo "ndk-build found at $NDK_DIR/ndk-build"
          "$NDK_DIR/ndk-build" --version || true
        else
          echo "Error: ndk-build not found at $NDK_DIR/ndk-build"
          exit 1
        fi

    # НОВЫЙ ШАГ: Установка libncurses5
    - name: Install libncurses5 (dependency for NDK r16b)
      run: |
        sudo apt-get update
        sudo apt-get install -y libncurses5

    - name: Set up Java (required by ndk-build in some contexts)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Build JNI with ndk-build
      run: |
        cd jni
        ndk-build APP_ABI="armeabi-v7a" V=1

    - name: Verify output file existence
      run: |
        OUTPUT_FILE="jni/libs/armeabi-v7a/libsampvoice.so"
        if [ -f "$OUTPUT_FILE" ]; then
          echo "File $OUTPUT_FILE found successfully!"
          ls -lh "$OUTPUT_FILE"
        else
          echo "Error: File $OUTPUT_FILE not found!"
          ls -R jni/libs || true
          exit 1
        fi

    - name: Upload compiled .so file
      uses: actions/upload-artifact@v4
      with:
        name: libsampvoice-so
        path: jni/libs/armeabi-v7a/libsampvoice.so
