name: Build JNI Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: actions/setup-ndk@v2 # Используйте актуальную версию экшна
      with:
        ndk-version: '21.4.7075529' # Пример: r21e. Замените на нужную вам версию NDK.
                                   # Если хотите r16b, попробуйте '16.1.4479499'.
                                   # Если он не найдет r16b, вам придется вручную скачать и настроить.

    - name: Build JNI with ndk-build
      run: |
        # actions/setup-ndk автоматически добавляет ndk-build в PATH
        # Вам, возможно, придется перейти в нужную директорию
        cd your_jni_project_folder
        ndk-build V=1

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: libsampvoice-so
        path: your_jni_project_folder/libs/armeabi-v7a/libsampvoice.so # Проверьте этот путь
