name: Build JNI Library with NDK r16b

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Используем Ubuntu, так как будем скачивать Linux-версию NDK

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and Extract Android NDK r16b
      run: |
        # URL для скачивания Linux x86 (64-bit) версии NDK r16b
        # Важно: убедитесь, что эта ссылка все еще работает!
        NDK_URL="https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip"
        NDK_DIR="$HOME/android-ndk-r16b"

        echo "Downloading NDK from $NDK_URL"
        curl -L "$NDK_URL" -o ndk.zip

        echo "Unzipping NDK to $NDK_DIR"
        unzip -q ndk.zip -d "$HOME"
        mv "$HOME/android-ndk-r16b" "$NDK_DIR" # Перемещаем, чтобы имя папки было чистым

        # Добавляем путь к ndk-build в PATH для текущего и последующих шагов
        echo "$NDK_DIR" >> $GITHUB_PATH
        echo "NDK_HOME=$NDK_DIR" >> $GITHUB_ENV # Устанавливаем NDK_HOME переменную окружения

        # Проверяем, что ndk-build доступен
        echo "Verifying ndk-build presence:"
        which ndk-build
        ndk-build --version || true # Должен показать версию или ошибку, если не найден

    - name: Set up Java (required by ndk-build in some contexts)
      # r16b может работать со старыми версиями Java, но лучше указать,
      # чтобы избежать проблем с более новыми версиями, которые не поддерживаются
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8' # Android NDK r16b лучше всего работает с Java 8

    - name: Build JNI with ndk-build
      run: |
        # !ВАЖНО!: Замените 'your_jni_project_folder' на реальный путь к вашей папке с JNI-исходниками
        # Например, если ваш Android.mk находится в 'app/src/main/jni', то это будет 'app/src/main'
        cd your_jni_project_folder

        # Если вам нужно указать конкретные ABI, используйте APP_ABI
        # Например, для сборки только под armeabi-v7a:
        ndk-build APP_ABI="armeabi-v7a" V=1

        # Если вы хотите собрать для всех поддерживаемых ABI (armeabi-v7a, arm64-v8a, x86, x86_64)
        # ndk-build V=1

    - name: Verify output file existence
      run: |
        # !ВАЖНО!: Замените 'your_jni_project_folder' на реальный путь
        OUTPUT_FILE="your_jni_project_folder/libs/armeabi-v7a/libsampvoice.so"
        if [ -f "$OUTPUT_FILE" ]; then
          echo "File $OUTPUT_FILE found successfully!"
          ls -lh "$OUTPUT_FILE"
        else
          echo "Error: File $OUTPUT_FILE not found!"
          # Показать содержимое папки libs для отладки
          ls -R your_jni_project_folder/libs || true
          exit 1
        fi

    - name: Upload compiled .so file
      uses: actions/upload-artifact@v4
      with:
        name: libsampvoice-so
        # !ВАЖНО!: Замените 'your_jni_project_folder' на реальный путь
        path: your_jni_project_folder/libs/armeabi-v7a/libsampvoice.so
