name: Build JNI with Windows NDK r16b

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        # Устанавливаем необходимые инструменты
        choco install -y 7zip curl

    - name: Download NDK from Google Drive
      run: |
        # Скачиваем через google-drive-downloader
        $fileId = "1ThXZY2oy-K1ycO489_9P7OO4evG4lcIT"
        $output = "ndk.zip"
        
        # Получаем подтверждающий код
        $confirmCode = (curl.exe -s -L -b "/tmp/cookies.txt" "https://drive.google.com/uc?export=download&id=$fileId" | Select-String -Pattern "confirm=([0-9A-Za-z_]+)" | ForEach-Object { $_.Matches.Groups[1].Value })
        
        if (-not $confirmCode) {
          $confirmCode = "t" # fallback
        }
        
        # Скачиваем файл с подтверждением
        curl.exe -L -b "/tmp/cookies.txt" "https://drive.google.com/uc?export=download&id=$fileId&confirm=$confirmCode" -o $output
        
        # Проверяем размер файла (должен быть больше 1MB)
        $fileInfo = Get-Item $output
        if ($fileInfo.Length -lt 1MB) {
          Write-Error "Downloaded file is too small! Probably failed to download."
          exit 1
        }

    - name: Extract NDK
      run: |
        7z x ndk.zip -o"$env:USERPROFILE\android-ndk-r16b" -y
        if (-not (Test-Path "$env:USERPROFILE\android-ndk-r16b\ndk-build.cmd")) {
          Write-Error "NDK extraction failed or ndk-build.cmd not found!"
          exit 1
        }
        echo "NDK_HOME=$env:USERPROFILE\android-ndk-r16b" >> $env:GITHUB_ENV
        echo "$env:USERPROFILE\android-ndk-r16b" >> $env:GITHUB_PATH

    - name: Verify NDK
      run: |
        echo "NDK contents:"
        dir "$env:NDK_HOME"
        call "$env:NDK_HOME\ndk-build.cmd" --version

    - name: Build JNI
      run: |
        cd $env:GITHUB_WORKSPACE
        call "$env:NDK_HOME\ndk-build.cmd" -C . clean
        call "$env:NDK_HOME\ndk-build.cmd" -C .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jni-libs
        path: libs/
