name: Build JNI

on:
  push:
    branches:
      - main # Или master, если у вас так называется основная ветка

jobs:
  build:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu (сейчас это 24.04)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- УДАЛИТЕ ЭТОТ ШАГ, ОН БОЛЬШЕ НЕ НУЖЕН И НЕ РАБОТАЕТ НА UBUNTU-LATEST ---
    # - name: Install libncurses5 (for old NDKs)
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y libncurses5
    # ----------------------------------------------------------------------

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1 # Используем экшн для установки NDK
      with:
        ndk-version: r21e # *** ИЗМЕНЕНИЕ ЗДЕСЬ: Указываем NDK r21e ***

    - name: Build JNI
      run: |
        ndk-build -C . clean
        ndk-build -C .

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jni-compiled-libraries
        path: libs/
