name: Build JNI

on:
  push:
    branches:
      - main # Или master, если у вас так называется основная ветка

jobs:
  build:
    # --- ИЗМЕНЕНИЕ ЗДЕСЬ: используем ubuntu-20.04 ---
    runs-on: ubuntu-20.04 # Используем Ubuntu 20.04, так как в ней ещё есть libncurses5
    # ------------------------------------------------

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install libncurses5 (for old NDKs)
      run: |
        sudo apt-get update
        sudo apt-get install -y libncurses5

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r16b # Укажите версию NDK, которую вы использовали (r16b)

    - name: Build JNI
      run: |
        ndk-build -C . clean
        ndk-build -C .

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jni-compiled-libraries
        path: libs/
